name: CD

# Run when tags are pushed
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        # includes caching and works with yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn build
        env:
          CI: false
          REACT_APP_NETWORK: mainnet
          REACT_APP_BSC_MM_ENABLED: ${{ secrets.REACT_APP_BSC_MM_ENABLED }}
          REACT_APP_MEWCONNECT_ENABLED: ${{ secrets.REACT_APP_MEWCONNECT_ENABLED }}
          REACT_APP_INFURA_ID: ${{ secrets.REACT_APP_INFURA_ID }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_ENABLED_CURRENCIES: "BTC,BCH,ZEC,DOGE"
      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
